import { sample } from 'st-utils';

const DESCRIPTIONS = [
  'Cometa 2/2',
  'Polishop',
  'Cometa',
  'Canva 11/12',
  'TAG Livros 9/12',
  'Leroy 4/4',
  'Shopee 3/4',
  'Presente Kariza 2/2',
  'PetLove 2/2',
  'Leroy 2/2',
  'CZ10 2/2',
  'Almoço',
  'Drogasil',
  'Ifood',
  'Almoço',
  'AmazonPrime',
  'Apple Armazenamento',
  'Tadah 1/3',
  'Estoril (Ifood)',
  'GymPass',
  'Uber Paim',
  'Uber Posto',
  'DoceBella',
  'LalaMove',
  'LalaMove',
  'NuttyBavarian',
  'PriscilaGamino',
  'HBOMax',
  'Santomé',
  'Rodoserv',
  'Ifood',
  'Leroy',
  'ML 1/2',
  'ML',
  'Shein 1/4',
  'Sobrancelha',
  'Daiso',
  'ML Presente Pai',
  'Uber Jovian',
  'Uber Flash',
  'Amazon Colheres',
  'Drogaria SP',
  'Disk Burguer',
  'Uber',
  'Uber Japa',
  'Japa',
  'Amazon 1/2',
  'Amazon',
  'Estoril (Ifood)',
  'Ifood',
  'Uber Achiropita',
  'Padaria',
  'Churras Cartão Gui',
  'Outback',
  'Picanharia do Gaucho',
  'Cometa 1/2',
  'Suporte',
  'Baladinha',
  'Bar Jovian',
  'Sacolão',
  'Canva 10/12',
  'TAG Livros 8/12',
  'Leroy 3/4',
  'Amazon 2/2 copo',
  'Shopee 2/4',
  'PoloWear 2/2',
  'Uber',
  'Almoço',
  'Sacolão',
  'Elarbi',
  'Uber',
  'Docebella',
  'AmazonPrime',
  'Ifood',
  'Apple Armazenamento',
  'Docebella',
  'HBOMax',
  'Presente Kariza 1/2',
  'Ifood',
  'Uber Casa Kariza',
  'Uber Anime Friends',
  'Spetoo',
  'Uber Adriata',
  'Sacolão',
  'PetLove 1/2',
  'Shopee Tintas',
  'Leroy 1/2',
  'Ticket360',
  'Adriata',
  'Uber Adriata',
  'Coutinho',
  'Uber',
  'Ifood',
  'Casa de Bolos',
  'Almoço',
  'CZ10 1/2',
  'Almoço',
  'Lanche Shopping',
  'Donuts',
  'Uber Shopping',
  'Ferramentas',
  'Picolé',
  'Uber Kariza',
  'Cometa 2/2',
  'Bar do Urso',
  'Decathlon Tenis',
  'Canva 9/12',
  'TAG Livros 7/12',
  'VRBO 4/4',
  'Tadah (Cadeiras) 3/3',
  'Leroy 2/4',
  'Ifood',
  'Fartura',
  'Ikesaki',
  'Rihappy',
  'BK',
  'Uber',
  'AmazonPrime',
  'Uber',
  'Apple Armazenamento',
  'Capinhas',
  'Boticario',
  'Amazon 1/2 copo',
  'Andorinha Passagem Assis',
  'Shopee',
  'Shopee 1/4',
  'Amazon Papa Bolinhas',
  'Uber',
  'Drogasil',
  'Picolé',
  'HBO',
  'YokoSo',
  'PoloWear 1/2',
  'Sacolao Fartura',
  'Drogasil',
  'Sumire Assis',
  'ifood',
  'Uber Holy Burger',
  'Uber',
  'Daki',
  'PetLove',
  'Tosa Mio',
  'Uber',
  'Ifood',
  'Capinhas',
  'Cine Bar',
  'Cometa 1/2',
  'Canva 8/12',
  'TAG Livros 6/12',
  'Dafiti Sol Presente Mãe 3/3',
  'Shein 3/3',
  'VRBO 3/4',
  'Tadah (Cadeiras) 2/3',
  'Uber Hospital',
  'Ifood',
  'Rifa Joia',
  'Padouro',
  'DoceBella',
  'Farmacia',
  'Ikesaki',
  'AmazonPrime',
  'Uber Shop Tucuruvi',
  'Apple Armazenamento',
  'Uber casa Armando',
  'Uber casa Armando',
  'Ingressos Paranoia',
  'Fralda Mio',
  'HBOMax',
  'Drogasil',
  'Cinemark Pipoca',
  '99Taxi Shopping',
  'Elarbi',
  'Leroy 1/4',
  'Uber Leroy',
  'Pintura Quarto',
  'Ifood',
  'Perfumaria',
  'Ifood',
  'ML',
  'Amazon Tranqueiras',
  'ML',
  'Cinema (dividir - lanche)',
  'ClickBus Praia',
  'Uber Praia',
  'Origamid 12/12',
  'Canva 7/12',
  'TAG Livros 5/12',
  'Beyoung presente Jannifer 2/2',
  'Climatizador 2/2',
  'Piticas 2/2',
  'Dafiti Sol Presente Mãe 2/3',
  'Shein 2/3',
  'VRBO 2/4',
  'Ifood',
  'Uber Circus Ida',
  'Uber Circus Volta',
  'Circus',
  'Pod Elarbi',
  'Renner Shorts',
  'Uber Volta Shopping',
  'Tadah (Cadeiras) 1/3',
  'AmazonPrime',
  'Apple Armazenamento',
  'Uber Ida Endocrino',
  'Exame Bioimpedancia',
  'Padaria PaDouro',
  'Uber Volta Endocrino',
  'Uber Volta Cinema',
  'Cinema Agua',
  'Ifood Almoço Domingo',
  'Farmacia Carverol',
  'HBOMax',
  'PetLove Areia',
  'Sobrancelha',
  'Ikesaki',
  'Uber Volta Shopping',
  'Sacaria Malu',
  'Elarbi',
  'Ifood',
  'ML Chinelo',
  'Uber Cancelamento',
  'Uber',
  'Elarbi',
  'Praia Quiosque',
  'BK',
  'Banca Cooler',
  'Pao de Acucar Praia',
  'BK',
  'Uber Rodo',
  'Ifood Sushi',
  'Ifood',
  'Casa de Bolo',
  'Ifood',
  'Drogasil',
  'Uber',
  'Ingresso Cinema',
  'Sacolao',
  'Pet Love 3/3',
  'Origamid 11/12',
  'Canva 6/12',
  'TAG Livros 4/12',
  'Farmacia Manipulacao 2/2',
  'Roupa de Cama 2/2',
  'Beyoung',
  'Amazon Refil Inseticida',
  'Ifood',
  'Ifood',
  'Ifood',
  'AmazonPrime',
  'Apple Armazenamento',
  'Apoia-se',
  'Beyoung presente Jannifer 1/2',
  'Shoppe comprinhas',
  'Climatizador 1/2',
  'Elarbi',
  'HBOMax',
  'Bar Armazem Piola',
  'Uber Armazem Piola',
  'Dafiti Sol Presente Mãe 1/3',
  'Cinemark Pipoca',
  'Uber Cinema',
  'Ifood',
  'Uber Shopping',
  'Ikesaki',
  'Piticas 1/2',
  'Casa de Bolos',
  'Shein 1/3',
  'Uber Flash (chave)',
  'Lanchonete rodoviaria',
  'Invernada',
  'Invernada Bolachas',
  'Bolo Mae',
  'Uber Adriata',
  'Adriata',
  'Ifood',
  'Farmacia',
  'Distribuidora',
  'VRBO 1/4',
  'Fartura',
  'Ifood',
  'Uber Exames',
  '99taxi exames',
  'Ifood',
  'Swift',
  'Caetanos',
  'Ludus',
  'Origamid 10/12',
  'Mala 6/6',
  'Canva 5/12',
  'TAG Livros 3/12',
  'Renner 2/2',
  'Shopping 2/2',
  'Pet Love 2/2',
  'Pet Love 2/3',
  'Farmacia Manipulacao 1/2',
  '99Taxi Apple Shop Morumbi',
  'Amazon',
  'Ifood',
  'Pod Elarbi',
  'Uber Volta Niver Jannifer',
  'Apple Armazenamento',
  '99Taxi Consulta Endocrino',
  'Apoia-se',
  'Ifood',
  'Amazon Compras Travesseiros',
  'Submarino Smart Lampada',
  'Ikesaki',
  'Riachuelo',
  'Lanche Shopping',
  'Uber Ida Rodoviaria',
  'HBOMax',
  'Ifood',
  'Uber Exames',
  'Precolandia',
  'Roupa de Cama 1/2',
  'Cortina',
  'Ifood',
  'Uber Exames',
  'Uber Flash',
  'Estoril',
  'Outback',
  'Uber Volta Apple Morumbi',
  'Uber Volta Shopping Tucuruvi',
  'Uber Volta Ludus',
  'iRobot Filtros 2/2',
  'Cometa 2/2',
  'Swift',
  'Caetanos',
  'Origamid 9/12',
  'Mala 5/6',
  'Canva 4/12',
  'Compras Shoppe 2/2',
  'Tenis Nando 2/2',
  'Ponto Frio Mãe 2/2',
  'TAG Livros 2/12',
  'Renner Presente Pai 2/2',
  'Rodoserv',
  'Ifood',
  'Amazon',
  'Uber',
  'Ikesaki',
  'Renner 1/2',
  'Apple Armazenamento',
  'Ifood',
  'Ikesaki',
  'Shopping 1/2',
  'Pet Love 1/2',
  'Apoia-se',
  'Uber',
  'Uber',
  'HBO Max',
  'Amazon',
  'Brocas',
  'Ifood',
  'Uber',
  'Nutricionista',
  '99Taxi',
  'Uber',
  'Sushi',
  'Amazon',
  'Ifood',
  'Sobrancelha',
  'Cacau Show',
  'Uber',
  'Daki',
  'B M',
  'Uber',
  'Pet Love 1/3',
];

export function getMockDescription(): string {
  return sample(DESCRIPTIONS);
}
